name: Hello World Action

description: A custom action that prints a hello message

inputs:
  names:
    description: The message to print
    required: true

runs:
  using: "composite"
  steps:
    - name: Set Greeting
      run: echo "Hello ${{ input.names }}."
      shell: bash