name: Hello World Action

description: A custom action that prints a hello message

inputs:
  message:
    description: The message to print
    required: true
    default: 'World'

runs:
  using: "composite"
  steps:
    - name: Set Greeting
      run: echo "$INPUT_WHO_TO_GREET"
      shell: bash
      env:
        INPUT_WHO_TO_GREET: ${{ inputs.message }}