name: Hello World Action

description: A custom action that prints a hello message

inputs:
  who-to-greed:
    description: The message to print
    required: true

runs:
  using: "composite"
  steps:
    - name: Set Greeting
      run: echo "${{ inputs.who-to-greed }}"
      shell: bash