name: Hello World

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/5 * * * *"

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        uses: ./.github/actions/greeting
        with:
          message: "Hello, ${{ github.event.pull_request.title }}"